### PR TITLE
sync with upstream (v4.9-rc3)

### PR DESCRIPTION
**Pull request by umiddelb**

### CODE REVIEW

**Comment by f1vefour** [comment]
Could you tell me why this branch is dirty?

Using git it appears to be a single file.

`git diff-index --name-only HEAD`

Which returns: `arch/arm/crypto/aesbs-core.S_shipped`

Any thoughts?

**Comment by umiddelb** [comment]
I've no idea, you may just wait for the next sync.

**Comment by umiddelb** [comment]
You may just try it once again, I've synced the master branch to 4.9-rc4.

**Comment by f1vefour** [comment]
I pulled again, the branch is clean.

**Pull request merged**
